import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Session, getServerSession } from "next-auth";
import authConfig from "@/lib/authConfig";
import Header from "@/components/shared/Header";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/shared/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session : Session | null = await getServerSession(authConfig)

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header session={session}/>
          {children}
        </Providers>
        <Footer/>
        <Toaster/>
      </body>
    </html>
  );
}
